/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TeamRouteImport } from './routes/team'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as PurchaseIndexRouteImport } from './routes/purchase.index'
import { Route as PurchaseIdRouteImport } from './routes/purchase.$id'
import { Route as QuotationsIndexRouteImport } from './routes/quotations.index'
import { Route as QuotationsIdRouteImport } from './routes/quotations.$id'
import { Route as RfqsIndexRouteImport } from './routes/rfqs.index'
import { Route as RfqsIdRouteImport } from './routes/rfqs.$id'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIndexRoute = PurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIdRoute = PurchaseIdRouteImport.update({
  id: '/purchase/$id',
  path: '/purchase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIndexRoute = QuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIdRoute = QuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqsIndexRoute = RfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqsIdRoute = RfqsIdRouteImport.update({
  id: '/rfqs/$id',
  path: '/rfqs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/customers/$id': typeof CustomersIdRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/rfqs/': typeof RfqsIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/customers/$id': typeof CustomersIdRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
  '/customers': typeof CustomersIndexRoute
  '/purchase': typeof PurchaseIndexRoute
  '/quotations': typeof QuotationsIndexRoute
  '/rfqs': typeof RfqsIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/customers/$id': typeof CustomersIdRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/rfqs/': typeof RfqsIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/followups'
    | '/leads'
    | '/notifications'
    | '/reports'
    | '/suppliers'
    | '/team'
    | '/customers/$id'
    | '/purchase/$id'
    | '/quotations/$id'
    | '/rfqs/$id'
    | '/customers/'
    | '/purchase/'
    | '/quotations/'
    | '/rfqs/'
    | '/api/public/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/followups'
    | '/leads'
    | '/notifications'
    | '/reports'
    | '/suppliers'
    | '/team'
    | '/customers/$id'
    | '/purchase/$id'
    | '/quotations/$id'
    | '/rfqs/$id'
    | '/customers'
    | '/purchase'
    | '/quotations'
    | '/rfqs'
    | '/api/public/mcp'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/auth'
    | '/followups'
    | '/leads'
    | '/notifications'
    | '/reports'
    | '/suppliers'
    | '/team'
    | '/customers/$id'
    | '/purchase/$id'
    | '/quotations/$id'
    | '/rfqs/$id'
    | '/customers/'
    | '/purchase/'
    | '/quotations/'
    | '/rfqs/'
    | '/api/public/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  FollowupsRoute: typeof FollowupsRoute
  LeadsRoute: typeof LeadsRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  SuppliersRoute: typeof SuppliersRoute
  TeamRoute: typeof TeamRoute
  CustomersIdRoute: typeof CustomersIdRoute
  PurchaseIdRoute: typeof PurchaseIdRoute
  QuotationsIdRoute: typeof QuotationsIdRoute
  RfqsIdRoute: typeof RfqsIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PurchaseIndexRoute: typeof PurchaseIndexRoute
  QuotationsIndexRoute: typeof QuotationsIndexRoute
  RfqsIndexRoute: typeof RfqsIndexRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/': {
      id: '/purchase/'
      path: '/purchase'
      fullPath: '/purchase/'
      preLoaderRoute: typeof PurchaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$id': {
      id: '/purchase/$id'
      path: '/purchase/$id'
      fullPath: '/purchase/$id'
      preLoaderRoute: typeof PurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/': {
      id: '/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof QuotationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/$id': {
      id: '/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof QuotationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfqs/': {
      id: '/rfqs/'
      path: '/rfqs'
      fullPath: '/rfqs/'
      preLoaderRoute: typeof RfqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfqs/$id': {
      id: '/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/rfqs/$id'
      preLoaderRoute: typeof RfqsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  FollowupsRoute: FollowupsRoute,
  LeadsRoute: LeadsRoute,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  SuppliersRoute: SuppliersRoute,
  TeamRoute: TeamRoute,
  CustomersIdRoute: CustomersIdRoute,
  PurchaseIdRoute: PurchaseIdRoute,
  QuotationsIdRoute: QuotationsIdRoute,
  RfqsIdRoute: RfqsIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PurchaseIndexRoute: PurchaseIndexRoute,
  QuotationsIndexRoute: QuotationsIndexRoute,
  RfqsIndexRoute: RfqsIndexRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
